# Generated by Django 3.1 on 2020-08-27 14:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Dairy_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Dairy Categories',
            },
        ),
        migrations.CreateModel(
            name='Add_Dairy_Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_dairy_category')),
            ],
            options={
                'verbose_name_plural': 'Add Dairy Product Types',
            },
        ),
        migrations.CreateModel(
            name='Add_Household_care_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Household_care Categories',
            },
        ),
        migrations.CreateModel(
            name='Add_Household_care_Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_household_care_category')),
            ],
            options={
                'verbose_name_plural': 'Add Household_care Product Types',
            },
        ),
        migrations.CreateModel(
            name='Add_Packaged_Food_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Packaged_Food Categories',
            },
        ),
        migrations.CreateModel(
            name='Add_Packaged_Food_Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_packaged_food_category')),
            ],
            options={
                'verbose_name_plural': 'Add Packaged_Food Product Types',
            },
        ),
        migrations.CreateModel(
            name='Add_Personal_Baby_care_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Personal_Baby_care Categories',
            },
        ),
        migrations.CreateModel(
            name='Add_Personal_Baby_care_Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_personal_baby_care_category')),
            ],
            options={
                'verbose_name_plural': 'Add Personal_Baby_care Product Types',
            },
        ),
        migrations.CreateModel(
            name='Add_Snacks_Beverages_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Snacks_Beverages Categories',
            },
        ),
        migrations.CreateModel(
            name='Add_Snacks_Beverages_Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_snacks_beverages_category')),
            ],
            options={
                'verbose_name_plural': 'Add Snacks_Beverages Product Types',
            },
        ),
        migrations.CreateModel(
            name='Add_Staples_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add Staples Categories',
            },
        ),
        migrations.CreateModel(
            name='Add_Staples_Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_staples_category')),
            ],
            options={
                'verbose_name_plural': 'Add Staples Product Types',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_weight', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=20)),
                ('total_price', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('order_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staples_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('category_Type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_staples_product_type')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_staples_category')),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Special_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Snacks_Beverages_Product_Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('category_Type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_snacks_beverages_product_type')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_snacks_beverages_category')),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('product_detail', jsonfield.fields.JSONField()),
                ('product_details', jsonfield.fields.JSONField()),
                ('total_price', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('full_address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('delevery_date_time', models.DateField(null=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('no_of_items', models.CharField(max_length=100)),
                ('order_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.order_status')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Baby_care_Product_Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('category_Type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_personal_baby_care_product_type')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_personal_baby_care_category')),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Packaged_Food_Product_Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('category_Type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_packaged_food_product_type')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_packaged_food_category')),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Household_care_Product_Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('category_Type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_household_care_product_type')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_household_care_category')),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Deal_of_The_Weak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Dairy_Product_Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_actual_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_fullname', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('category_Type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_dairy_product_type')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organicaisleApp.add_dairy_category')),
                ('product_offer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='organicaisleApp.offer')),
            ],
        ),
    ]
