# Generated by Django 3.1 on 2020-08-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organicaisleApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy_product_add',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='deal_of_the_weak',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='household_care_product_add',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='packaged_food_product_add',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='personal_baby_care_product_add',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='snacks_beverages_product_add',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='special_offer',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='staples_product',
            name='unique_id',
        ),
    ]
