# Generated by Django 3.1 on 2020-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organicaisleApp', '0003_auto_20200829_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='SliderType',
        ),
    ]
