# Generated by Django 3.1 on 2020-08-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organicaisleApp', '0004_auto_20200829_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unique_id',
        ),
    ]
